### ISSUE TITLE
PCA causes a value error

### ISSUE THREAD

**Issue by brookehus** [msmbuilder/osprey#105]
For `('pca', PCA())` in the configuration file, this is the error I get. cc: @cxhernandez 

```
------------------------------------------------------------------------------
Exception encountered while fitting model
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bhusic/source/osprey/osprey/execute_worker.py", line 125, in run_single_trial
    estimator, params, cv=cv, scoring=scoring, X=X, y=y, verbose=1)
  File "/home/bhusic/source/osprey/osprey/fit_estimator.py", line 59, in fit_and_score_estimator
    for train, test in cv)
  File "/home/bhusic/miniconda3/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/bhusic/miniconda3/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/bhusic/miniconda3/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/home/bhusic/miniconda3/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/home/bhusic/miniconda3/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/bhusic/source/osprey/osprey/fit_estimator.py", line 124, in _fit_and_score
    estimator.fit(X_train, **fit_params)
  File "/home/bhusic/miniconda3/lib/python2.7/site-packages/sklearn/pipeline.py", line 164, in fit
    Xt, fit_params = self._pre_transform(X, y, **fit_params)
  File "/home/bhusic/miniconda3/lib/python2.7/site-packages/sklearn/pipeline.py", line 145, in _pre_transform
    Xt = transform.fit_transform(Xt, y, **fit_params_steps[name])
  File "/home/bhusic/miniconda3/lib/python2.7/site-packages/sklearn/decomposition/pca.py", line 241, in fit_transform
    U, S, V = self._fit(X)
  File "/home/bhusic/miniconda3/lib/python2.7/site-packages/sklearn/decomposition/pca.py", line 268, in _fit
    X = check_array(X)
  File "/home/bhusic/miniconda3/lib/python2.7/site-packages/sklearn/utils/validation.py", line 393, in check_array
    array = array.astype(np.float64)
ValueError: setting an array element with a sequence.
------------------------------------------------------------------------------
```

**Comment by mpharrigan** [comment]
Are you using the msmbuilder pca class or just the sklearn one?

**Comment by brookehus** [comment]
Not sure, how can I make sure it's the msmb one? Can I do that in the osprey config file?

**Comment by mpharrigan** [comment]
I assume the crazy voodoo here https://github.com/msmbuilder/osprey/blob/master/osprey/eval_scopes.py#L25 is somehow resulting in both the msmbuilder PCA and sklearn PCA being found, and the msmbuilder version losing.

You can make your pipeline in a legit python script and save it via pickle, and use that instead of specifying the pipeline in the config file

**Comment by brookehus** [comment]
Is that the best solution?

**Comment by cxhernandez** [comment]
No, we should fix it.

**Comment by cxhernandez** [comment]
I think the issue is that [msmbuilder.decomposition.PCA](https://github.com/msmbuilder/msmbuilder/blob/599cedb5c39b6d7a624558323687dae7cfa15fd6/msmbuilder/decomposition/pca.py) doesn't inherit `BaseEstimator`, so it doesn't get selected by osprey @ [eval_scopes.py#L31](https://github.com/msmbuilder/osprey/blob/master/osprey/eval_scopes.py#L31).

**Comment by mpharrigan** [comment]
that's not it. sklearn's pca already inherits from baseestimator

**Comment by cxhernandez** [comment]
> that's not it. sklearn's pca already inherits from baseestimator
good point.... :disappointed: 

Hmm. Out of curiousity, @brookehus, what do you have set as the `entry_point` in your `.yaml` file?

**Comment by cxhernandez** [comment]
Okay, what was happening is that sklearn's `PCA` was overwriting msmbuilder's in the `results` dict @ [eval_scopes.py#L43-L44](https://github.com/msmbuilder/osprey/blob/master/osprey/eval_scopes.py#L43-L44)

**Comment by mpharrigan** [comment]
> Okay, what was happening is that sklearn's PCA was overwriting msmbuilder's in the result dict @ eval_scopes.py#L43-L44

That's what I said!

**Comment by cxhernandez** [comment]
Well you didn't explain why it was losing! :stuck_out_tongue_winking_eye:
