### ISSUE TITLE
osprey dump error

### ISSUE THREAD

**Issue by jeiros** [msmbuilder/osprey#136]
I'm getting the following error after issuing the `osprey dump -o json osprey-trials.db`:
```
An unexpected error has occurred with osprey (version 1.0.0.dev0), please
consider sending the following traceback to the osprey GitHub issue tracker at:
        https://github.com/pandegroup/osprey/issues

Traceback (most recent call last):
  File "/Users/je714/anaconda/lib/python3.4/site-packages/yaml/reader.py", line 157, in update
    'strict', self.eof)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 98: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/je714/anaconda/bin/osprey", line 9, in <module>
    load_entry_point('osprey==1.0.0.dev0', 'console_scripts', 'osprey')()
  File "/Users/je714/anaconda/lib/python3.4/site-packages/osprey-1.0.0.dev0-py3.4.egg/osprey/cli/main.py", line 37, in main
    args_func(args, p)
  File "/Users/je714/anaconda/lib/python3.4/site-packages/osprey-1.0.0.dev0-py3.4.egg/osprey/cli/main.py", line 42, in args_func
    args.func(args, p)
  File "/Users/je714/anaconda/lib/python3.4/site-packages/osprey-1.0.0.dev0-py3.4.egg/osprey/cli/parser_dump.py", line 8, in func
    execute(args, parser)
  File "/Users/je714/anaconda/lib/python3.4/site-packages/osprey-1.0.0.dev0-py3.4.egg/osprey/execute_dump.py", line 11, in execute
    config = Config(args.config, verbose=False)
  File "/Users/je714/anaconda/lib/python3.4/site-packages/osprey-1.0.0.dev0-py3.4.egg/osprey/config.py", line 64, in __init__
    config = parse(f)
  File "/Users/je714/anaconda/lib/python3.4/site-packages/osprey-1.0.0.dev0-py3.4.egg/osprey/config.py", line 329, in parse
    res = yaml.load(f)
  File "/Users/je714/anaconda/lib/python3.4/site-packages/yaml/__init__.py", line 70, in load
    loader = Loader(stream)
  File "/Users/je714/anaconda/lib/python3.4/site-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/Users/je714/anaconda/lib/python3.4/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/Users/je714/anaconda/lib/python3.4/site-packages/yaml/reader.py", line 135, in determine_encoding
    self.update(1)
  File "/Users/je714/anaconda/lib/python3.4/site-packages/yaml/reader.py", line 165, in update
    exc.encoding, exc.reason)
yaml.reader.ReaderError: unacceptable character #x00e9: invalid continuation byte
  in "osprey-trials.db", position 98
```
I installed ospray through direct download of the github repo.

**Comment by jeiros** [comment]
My mistake, I should be parsing the config.yml file :sweat_smile:
