### ISSUE TITLE
Osprey plot command error: 'error making plot4 for featurizer__types''

### ISSUE THREAD

**Issue by jeiros** [msmbuilder/osprey#138]
Hello there, 
I'm getting the following error when using the `osprey plot osprey_config.yml ` command:
```
error making plot4 for 'featurizer__types'
An unexpected error has occurred with osprey (version 1.0.0.dev0), please
consider sending the following traceback to the osprey GitHub issue tracker at:
        https://github.com/pandegroup/osprey/issues

Traceback (most recent call last):
  File "/Users/je714/anaconda/bin/osprey", line 9, in <module>
    load_entry_point('osprey==1.0.0.dev0', 'console_scripts', 'osprey')()
  File "/Users/je714/anaconda/lib/python3.4/site-packages/osprey-1.0.0.dev0-py3.4.egg/osprey/cli/main.py", line 37, in main
    args_func(args, p)
  File "/Users/je714/anaconda/lib/python3.4/site-packages/osprey-1.0.0.dev0-py3.4.egg/osprey/cli/main.py", line 42, in args_func
    args.func(args, p)
  File "/Users/je714/anaconda/lib/python3.4/site-packages/osprey-1.0.0.dev0-py3.4.egg/osprey/cli/parser_plot.py", line 8, in func
    execute(args, parser)
  File "/Users/je714/anaconda/lib/python3.4/site-packages/osprey-1.0.0.dev0-py3.4.egg/osprey/execute_plot.py", line 39, in execute
    bk.show(p)
  File "/Users/je714/anaconda/lib/python3.4/site-packages/bokeh/io.py", line 301, in show
    return _show_with_state(obj, _state, browser, new)
  File "/Users/je714/anaconda/lib/python3.4/site-packages/bokeh/io.py", line 315, in _show_with_state
    _show_file_with_state(obj, state, new, controller)
  File "/Users/je714/anaconda/lib/python3.4/site-packages/bokeh/io.py", line 320, in _show_file_with_state
    save(obj, state=state)
  File "/Users/je714/anaconda/lib/python3.4/site-packages/bokeh/io.py", line 376, in save
    _save_helper(obj, filename, resources, title, validate)
  File "/Users/je714/anaconda/lib/python3.4/site-packages/bokeh/io.py", line 413, in _save_helper
    doc.validate()
  File "/Users/je714/anaconda/lib/python3.4/site-packages/bokeh/document.py", line 893, in validate
    check_integrity(refs)
  File "/Users/je714/anaconda/lib/python3.4/site-packages/bokeh/core/validation/check.py", line 22, in check_integrity
    messages[func.validator_type].extend(func())
  File "/Users/je714/anaconda/lib/python3.4/site-packages/bokeh/core/validation/decorators.py", line 23, in wrapper
    extra = func(*args, **kw)
  File "/Users/je714/anaconda/lib/python3.4/site-packages/bokeh/models/sources.py", line 220, in _check_column_lengths
    lengths = set(len(x) for x in self.data.values())
  File "/Users/je714/anaconda/lib/python3.4/site-packages/bokeh/models/sources.py", line 220, in <genexpr>
    lengths = set(len(x) for x in self.data.values())
TypeError: object of type 'map' has no len()
```
[Here](http://lpaste.net/5629289965578878976)  is the `osprey_config.yml` file.
Looks like the problem is with the bokeh package, but it looks like I have the latest version:
```
$ conda update bokeh
Fetching package metadata: ........
# All requested packages already installed.
# packages in environment at /Users/je714/anaconda:
#
bokeh                     0.11.1                   py34_0
```
Thanks for any help on this!

**Comment by cxhernandez** [comment]
Thanks for the report @jeiros! Would you happen to have an example DB, for which this error occurs?

**Comment by jeiros** [comment]
Hi there, I reported the config file since that is what `osprey plot` seems to parse. Please find attached the associated DB file.
[osprey-trials.db.zip](https://github.com/msmbuilder/osprey/files/220695/osprey-trials.db.zip)

**Comment by jeiros** [comment]
Where you able to replicate the error @cxhernandez ? The DB file is the same one that's giving the error in the `current_best` [issue](https://github.com/msmbuilder/osprey/issues/139) I opened as well.

**Comment by cxhernandez** [comment]
Hey @jeiros! I've been busy with other work this week, but I'll try to take a look at this over the weekend.

**Comment by cxhernandez** [comment]
Okay, so the problem (for https://github.com/msmbuilder/osprey/issues/139 at least) seems to be that numpy can't handle `None` values in a list. I'll try to work on a PR soon

**Comment by cxhernandez** [comment]
And the error for this issue comes from [plot.py#L96](https://github.com/msmbuilder/osprey/blob/master/osprey/plot.py#L96), which needs to be converted to a list.

**Comment by cxhernandez** [comment]
Also, plot4 doesn't seem to work for enums, so that will have to be fixed at some point.

**Comment by cxhernandez** [comment]
fixed in https://github.com/msmbuilder/osprey/pull/146
