### ISSUE TITLE
Osprey current_best command error: 'AttributeError: 'list' object has no attribute 'argmax''

### ISSUE THREAD

**Issue by jeiros** [msmbuilder/osprey#139]
Hi there, 

I've also encountered the following error when using the `osprey current_best osprey_config.yml` command:
```
An unexpected error has occurred with osprey (version 1.0.0.dev0), please
consider sending the following traceback to the osprey GitHub issue tracker at:
        https://github.com/pandegroup/osprey/issues

Traceback (most recent call last):
  File "/Users/je714/anaconda/lib/python3.4/site-packages/numpy/core/fromnumeric.py", line 965, in argmax
    argmax = a.argmax
AttributeError: 'list' object has no attribute 'argmax'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/je714/anaconda/bin/osprey", line 9, in <module>
    load_entry_point('osprey==1.0.0.dev0', 'console_scripts', 'osprey')()
  File "/Users/je714/anaconda/lib/python3.4/site-packages/osprey-1.0.0.dev0-py3.4.egg/osprey/cli/main.py", line 37, in main
    args_func(args, p)
  File "/Users/je714/anaconda/lib/python3.4/site-packages/osprey-1.0.0.dev0-py3.4.egg/osprey/cli/main.py", line 42, in args_func
    args.func(args, p)
  File "/Users/je714/anaconda/lib/python3.4/site-packages/osprey-1.0.0.dev0-py3.4.egg/osprey/cli/parser_currentbest.py", line 10, in func
    execute(args, parser)
  File "/Users/je714/anaconda/lib/python3.4/site-packages/osprey-1.0.0.dev0-py3.4.egg/osprey/execute_currentbest.py", line 18, in execute
    c_b_m = items[np.argmax([i["mean_test_score"] for i in items])]
  File "/Users/je714/anaconda/lib/python3.4/site-packages/numpy/core/fromnumeric.py", line 967, in argmax
    return _wrapit(a, 'argmax', axis, out)
  File "/Users/je714/anaconda/lib/python3.4/site-packages/numpy/core/fromnumeric.py", line 48, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
TypeError: unorderable types: NoneType() > float()
```
The config file is the same as the issue [#138](https://github.com/msmbuilder/osprey/issues/138) I've just opened.

Cheers,
Juan

**Comment by cxhernandez** [comment]
Again, would be helpful to have example DB. Nothing immediately obvious stands out.

**Comment by cxhernandez** [comment]
fixed in https://github.com/msmbuilder/osprey/pull/146
