### ISSUE TITLE
error with gp search

### ISSUE THREAD

**Issue by msultan** [msmbuilder/osprey#143]
I am getting the following issue with gp serach. any ideas what might be happening? 
```
Beginning iteration                                            1 / 200
----------------------------------------------------------------------
Loading trials database: sqlite:///osprey-trials.db...
History contains: 1 trials
Choosing next hyperparameters with gp...
unexpected array size: new_size=1, got array with arr_size=0
 /home/msultan/software/anaconda/lib/python3.5/site-packages/mdtraj/formats/pdb/pdbfile.py:193: UserWarning:Unlikely unit cell vectors detected in PDB file likely resulting from a dummy CRYST1 record. Discarding unit cell vectors.
An unexpected error has occurred with osprey (version 1.0.0.dev0), please
consider sending the following traceback to the osprey GitHub issue tracker at:
        https://github.com/pandegroup/osprey/issues

Traceback (most recent call last):
  File "/home/msultan/software/anaconda/bin/osprey", line 9, in <module>
    load_entry_point('osprey==1.0.0.dev0', 'console_scripts', 'osprey')()
  File "/home/msultan/software/anaconda/lib/python3.5/site-packages/osprey-1.0.0.dev0-py3.5.egg/osprey/cli/main.py", line 37, in main
    args_func(args, p)
  File "/home/msultan/software/anaconda/lib/python3.5/site-packages/osprey-1.0.0.dev0-py3.5.egg/osprey/cli/main.py", line 42, in args_func
    args.func(args, p)
  File "/home/msultan/software/anaconda/lib/python3.5/site-packages/osprey-1.0.0.dev0-py3.5.egg/osprey/cli/parser_worker.py", line 8, in func
    execute(args, parser)
  File "/home/msultan/software/anaconda/lib/python3.5/site-packages/osprey-1.0.0.dev0-py3.5.egg/osprey/execute_worker.py", line 77, in execute
    sessionbuilder=config.trialscontext)
  File "/home/msultan/software/anaconda/lib/python3.5/site-packages/osprey-1.0.0.dev0-py3.5.egg/osprey/execute_worker.py", line 102, in initialize_trial
    params = strategy.suggest(history, searchspace)
  File "/home/msultan/software/anaconda/lib/python3.5/site-packages/osprey-1.0.0.dev0-py3.5.egg/osprey/strategies.py", line 277, in suggest
    self._create_kernel(V)
  File "/home/msultan/software/anaconda/lib/python3.5/site-packages/osprey-1.0.0.dev0-py3.5.egg/osprey/strategies.py", line 194, in _create_kernel
    self._kernf = Fixed(self.n_dims, tdot(V))
  File "/home/msultan/software/anaconda/lib/python3.5/site-packages/GPy/util/linalg.py", line 324, in tdot
    return tdot_blas(*args, **kwargs)
  File "/home/msultan/software/anaconda/lib/python3.5/site-packages/GPy/util/linalg.py", line 318, in tdot_blas
    trans=0, lower=0)
_fblas.error: failed in converting 2nd keyword `c' of _fblas.dsyrk to C/Fortran array

```

**Comment by msultan** [comment]
this got fixed but another popped up
