### ISSUE TITLE
Can't load pickle

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/osprey#180]
```
$ osprey worker config.yaml 
======================================================================
= osprey is a tool for machine learning hyperparameter optimization. =
======================================================================

osprey version:      1.1.0dev0
time:                August 08, 2016 10:44 AM
hostname:            vspm58
cwd:                 /data/harrigan/compute/mdsmoove/fs-peptide/analysis/multi-landmarks/osprey
pid:                 11481

Loading config file:     config.yaml...
An unexpected error has occurred with osprey (version 1.1.0dev0), please
consider sending the following traceback to the osprey GitHub issue tracker at:
        https://github.com/pandegroup/osprey/issues

Traceback (most recent call last):
  File "/home/harrigan/opt/miniconda3/envs/msm/bin/osprey", line 9, in <module>
    load_entry_point('osprey==1.1.0.dev0', 'console_scripts', 'osprey')()
  File "/home/harrigan/opt/miniconda3/envs/msm/lib/python3.5/site-packages/osprey-1.1.0.dev0-py3.5.egg/osprey/cli/main.py", line 37, in main
    args_func(args, p)
  File "/home/harrigan/opt/miniconda3/envs/msm/lib/python3.5/site-packages/osprey-1.1.0.dev0-py3.5.egg/osprey/cli/main.py", line 42, in args_func
    args.func(args, p)
  File "/home/harrigan/opt/miniconda3/envs/msm/lib/python3.5/site-packages/osprey-1.1.0.dev0-py3.5.egg/osprey/cli/parser_worker.py", line 8, in func
    execute(args, parser)
  File "/home/harrigan/opt/miniconda3/envs/msm/lib/python3.5/site-packages/osprey-1.1.0.dev0-py3.5.egg/osprey/execute_worker.py", line 33, in execute
    estimator = config.estimator()
  File "/home/harrigan/opt/miniconda3/envs/msm/lib/python3.5/site-packages/osprey-1.1.0.dev0-py3.5.egg/osprey/config.py", line 209, in estimator
    estimator = cPickle.load(f)
AttributeError: Can't get attribute 'MytICA' on <module '__main__' from '/home/harrigan/opt/miniconda3/envs/msm/bin/osprey'>
```

**Comment by mpharrigan** [comment]
We should update the url in the "consider sending"

**Comment by mpharrigan** [comment]
http://stefaanlippens.net/pickleproblem

**Comment by cxhernandez** [comment]
Is this using the `joblib` loader like in our [example](http://msmbuilder.org/osprey/development/config_file.html#dataset-loader)?

**Comment by mpharrigan** [comment]
This is for the estimator

**Comment by cxhernandez** [comment]
Ah, okay. So #183 lets you import modules required by your pickled function/class?

**Comment by mpharrigan** [comment]
No, #183 is orthogonal
