### ISSUE TITLE
ImportError: No module named basesetup

### ISSUE THREAD

**Issue by rsatijaUT** [msmbuilder/osprey#255]
Hi, trying to install Osprey using pip, I encounter the following error:

login2.ls5(1002)$ pip install --user osprey
Collecting osprey
  Using cached https://files.pythonhosted.org/packages/63/ac/f472540e6eae60a6086829e5b17ea255227def0ccd17e015be39b49d307d/osprey-1.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-j2yU2e/osprey/setup.py", line 6, in <module>
        from basesetup import write_version_py
    ImportError: No module named basesetup
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-j2yU2e/osprey/

Does this have to do with any dependencies I am missing when installing using pip?

**Comment by rberg2** [comment]
Hello,

I have been having this problem as well. Has anybody found a solution yet? Some searching around the internet suggests msmbuilder or msmexplorer may have basesetup. And there is indeed a basesetup.py in msmexplorer.
I tried installing both but I still get this "ModuleNotFoundError: No module named 'basesetup'" error.
```
pip install git+https://github.com/msmbuilder/msmbuilder.git
pip install git+https://github.com/msmbuilder/msmexplorer.git
```

edit: I should mention for anyone reading this. This error happens when I follow the `pip install osprey` instruction on pypi.org. If I clone the repo and do a `python setup.py install` I do not get the basesetup error.
