### ISSUE TITLE
Database disk image is malformed

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/osprey#6]
```
An unexpected error has occurred with osprey (version 0.2_15_gf7419e1-py3.4.egg), please
consider sending the following traceback to the osprey GitHub issue tracker at:
                                                                               
        https://github.com/rmcgibbo/osprey/issues                              
                                                                               
Traceback (most recent call last):                                             
  File "/home/harrigan/opt/python/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 525, in _commit_impl
    self.engine.dialect.do_commit(self.connection)                             
  File "/home/harrigan/opt/python/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 409, in do_commit
    dbapi_connection.commit()                                                  
sqlite3.OperationalError: disk I/O error                                       
                                                                               
The above exception was the direct cause of the following exception:           
                                                                               
Traceback (most recent call last):                                             
  File "/home/harrigan/opt/python/bin/osprey", line 9, in <module>             
    load_entry_point('osprey==0.2-15-gf7419e1', 'console_scripts', 'osprey')() 
  File "/home/harrigan/opt/python/lib/python3.4/site-packages/osprey-0.2_15_gf7419e1-py3.4.egg/osprey/cli/main.py", line 33, in main
    args_func(args, p)                                                         
  File "/home/harrigan/opt/python/lib/python3.4/site-packages/osprey-0.2_15_gf7419e1-py3.4.egg/osprey/cli/main.py", line 38, in       args_func
    args.func(args, p)                                                         
  File "/home/harrigan/opt/python/lib/python3.4/site-packages/osprey-0.2_15_gf7419e1-py3.4.egg/osprey/cli/parser_worker.py", line 8,  in func
    execute(args, parser)                                                      
  File "/home/harrigan/opt/python/lib/python3.4/site-packages/osprey-0.2_15_gf7419e1-py3.4.egg/osprey/execute_worker.py", line 71, in execute
    params=params, cv=cv, config_sha1=config_sha1, session=session)            
  File "/home/harrigan/opt/python/lib/python3.4/site-packages/osprey-0.2_15_gf7419e1-py3.4.egg/osprey/execute_worker.py", line 89, in run_single_trial
    session.commit()                                                           
  File "/home/harrigan/opt/python/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 776, in commit
    self.transaction.commit()                                                  
  File "/home/harrigan/opt/python/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 381, in commit
    t[1].commit()                                                              
  File "/home/harrigan/opt/python/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1333, in commit
    self._do_commit()                                                          
  File "/home/harrigan/opt/python/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1364, in _do_commit
    self.connection._commit_impl()                                             
  File "/home/harrigan/opt/python/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 527, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)                    
  File "/home/harrigan/opt/python/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
    exc_info                                                                   
  File "/home/harrigan/opt/python/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)            
  File "/home/harrigan/opt/python/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 181, in reraise
    raise value.with_traceback(tb)                                             
  File "/home/harrigan/opt/python/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 525, in _commit_impl
    self.engine.dialect.do_commit(self.connection)                             
  File "/home/harrigan/opt/python/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 409, in do_commit
    dbapi_connection.commit()                                                  
sqlalchemy.exc.OperationalError: (OperationalError) disk I/O error None None   
```

**Comment by cxhernandez** [comment]
Has anyone else seen this?
